/*''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''
' ======================================================================
' Computer Vision/Image Processing Tool Project - Dr. Scott Umbaugh SIUE
' ======================================================================
'
'             File Name: Win32Msgs.cs
'           Description: Contains the controls and code
'                        for CustomControls->Win32Msgs class
'         Related Files: CvipConstant.cs
'   Initial Coding Date: April 2007
'              Modified: March 2010
'       Delevoping tool: Visual Studio 2010-C#
'             Credit(s): Patrick Solt
'                        Southern Illinois University Edwardsville
'
' Copyright (C) 2013 Scott Umbaugh and SIUE
'
' Permission to use, copy, modify, and distribute this software and its
' documentation for any non-commercial purpose and without fee is hereby
' granted, provided that the above copyright notice appear in all copies
' and that both that copyright notice and this permission notice appear
' in supporting documentation.  This software is provided "as is"
' without express or implied warranty.
'
'''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''*/

using System;

/// <summary>
/// Win32 message codes
/// </summary>
namespace CVIPGUI
{
    /// <summary>
    /// First message codes for sub message groups
    /// </summary>
    public enum BaseCodes : int
    {
        LVM_FIRST = 0x1000,
        TV_FIRST = 0x1100,
        HDM_FIRST = 0x1200,
        TCM_FIRST = 0x1300,
        PGM_FIRST = 0x1400,
        ECM_FIRST = 0x1500,
        BCM_FIRST = 0x1600,
        CBM_FIRST = 0x1700,
        CCM_FIRST = 0x2000,
        NM_FIRST = 0x0000,
        LVN_FIRST = (NM_FIRST - 100),
        HDN_FIRST = (NM_FIRST - 300),
    }

    /// <summary>
    /// Header message codes HDM_
    /// </summary>
    public enum HDM : int
    {
        HDM_FIRST = BaseCodes.HDM_FIRST,
        GETITEMCOUNT = (HDM_FIRST + 0),
        INSERTITEMA = (HDM_FIRST + 1),
        DELETEITEM = (HDM_FIRST + 2),
        GETITEMA = (HDM_FIRST + 3),
        SETITEMA = (HDM_FIRST + 4),
        LAYOUT = (HDM_FIRST + 5),
        HITTEST = (HDM_FIRST + 6),
        GETITEMRECT = (HDM_FIRST + 7),
        SETIMAGELIST = (HDM_FIRST + 8),
        GETIMAGELIST = (HDM_FIRST + 9),
        INSERTITEMW = (HDM_FIRST + 10),
        GETITEMW = (HDM_FIRST + 11),
        SETITEMW = (HDM_FIRST + 12),
        ORDERTOINDEX = (HDM_FIRST + 15),
        CREATEDRAGIMAGE = (HDM_FIRST + 16),
        GETORDERARRAY = (HDM_FIRST + 17),
        SETORDERARRAY = (HDM_FIRST + 18),
        SETHOTDIVIDER = (HDM_FIRST + 19),
        SETBITMAPMARGIN = (HDM_FIRST + 20),
        GETBITMAPMARGIN = (HDM_FIRST + 21),
        SETFILTERCHANGETIMEOUT = (HDM_FIRST + 22),
        EDITFILTER = (HDM_FIRST + 23),
        CLEARFILTER = (HDM_FIRST + 24)
    }

    /// <summary>
    /// Header notification message codes HDN_
    /// </summary>
    public enum HDN : int
    {
        HDN_FIRST = BaseCodes.HDN_FIRST,
        ITEMCHANGINGA = (HDN_FIRST - 0),
        ITEMCHANGINGW = (HDN_FIRST - 20),
        ITEMCHANGEDA = (HDN_FIRST - 1),
        ITEMCHANGEDW = (HDN_FIRST - 21),
        ITEMCLICKA = (HDN_FIRST - 2),
        ITEMCLICKW = (HDN_FIRST - 22),
        ITEMDBLCLICKA = (HDN_FIRST - 3),
        ITEMDBLCLICKW = (HDN_FIRST - 23),
        DIVIDERDBLCLICKA = (HDN_FIRST - 5),
        DIVIDERDBLCLICKW = (HDN_FIRST - 25),
        BEGINTRACKA = (HDN_FIRST - 6),
        BEGINTRACKW = (HDN_FIRST - 26),
        ENDTRACKA = (HDN_FIRST - 7),
        ENDTRACKW = (HDN_FIRST - 27),
        TRACKA = (HDN_FIRST - 8),
        TRACKW = (HDN_FIRST - 28),
        GETDISPINFOA = (HDN_FIRST - 9),
        GETDISPINFOW = (HDN_FIRST - 29),
        BEGINDRAG = (HDN_FIRST - 10),
        ENDDRAG = (HDN_FIRST - 11),
        FILTERCHANGE = (HDN_FIRST - 12),
        FILTERBTNCLICK = (HDN_FIRST - 13)
    }

    public enum HT : int
    {
        ERROR = -2,
        TRANSPARENT = -1,
        NOWHERE = 0,
        CLIENT = 1,
        CAPTION = 2,
        SYSMENU = 3,
        GROWBOX = 4,
        MENU = 5,
        HSCROLL = 6,
        VSCROLL = 7,
        MINBUTTON = 8,
        MAXBUTTON = 9,
        LEFT = 10,
        RIGHT = 11,
        TOP = 12,
        TOPLEFT = 13,
        TOPRIGHT = 14,
        BOTTOM = 15,
        BOTTOMLEFT = 16,
        BOTTOMRIGHT = 17,
        BORDER = 18,
        OBJECT = 19,
        CLOSE = 20,
        HELP = 21
    }

    /// <summary>
    /// ListView message codes LVM_
    /// </summary>
    public enum LVM : int
    {
        LVM_FIRST = BaseCodes.LVM_FIRST,
        GETBKCOLOR = (LVM_FIRST + 0),
        SETBKCOLOR = (LVM_FIRST + 1),
        GETIMAGELIST = (LVM_FIRST + 2),
        SETIMAGELIST = (LVM_FIRST + 3),
        GETITEMCOUNT = (LVM_FIRST + 4),
        GETITEMA = (LVM_FIRST + 5),
        GETITEMW = (LVM_FIRST + 75),
        SETITEMA = (LVM_FIRST + 6),
        SETITEMW = (LVM_FIRST + 76),
        INSERTITEMA = (LVM_FIRST + 7),
        INSERTITEMW = (LVM_FIRST + 77),
        DELETEITEM = (LVM_FIRST + 8),
        DELETEALLITEMS = (LVM_FIRST + 9),
        GETCALLBACKMASK = (LVM_FIRST + 10),
        SETCALLBACKMASK = (LVM_FIRST + 11),
        GETNEXTITEM = (LVM_FIRST + 12),
        FINDITEMA = (LVM_FIRST + 13),
        FINDITEMW = (LVM_FIRST + 83),
        GETITEMRECT = (LVM_FIRST + 14),
        SETITEMPOSITION = (LVM_FIRST + 15),
        GETITEMPOSITION = (LVM_FIRST + 16),
        GETSTRINGWIDTHA = (LVM_FIRST + 17),
        GETSTRINGWIDTHW = (LVM_FIRST + 87),
        HITTEST = (LVM_FIRST + 18),
        ENSUREVISIBLE = (LVM_FIRST + 19),
        SCROLL = (LVM_FIRST + 20),
        REDRAWITEMS = (LVM_FIRST + 21),
        ARRANGE = (LVM_FIRST + 22),
        EDITLABELA = (LVM_FIRST + 23),
        EDITLABELW = (LVM_FIRST + 118),
        GETEDITCONTROL = (LVM_FIRST + 24),
        GETCOLUMNA = (LVM_FIRST + 25),
        GETCOLUMNW = (LVM_FIRST + 95),
        SETCOLUMNA = (LVM_FIRST + 26),
        SETCOLUMNW = (LVM_FIRST + 96),
        INSERTCOLUMNA = (LVM_FIRST + 27),
        INSERTCOLUMNW = (LVM_FIRST + 97),
        DELETECOLUMN = (LVM_FIRST + 28),
        GETCOLUMNWIDTH = (LVM_FIRST + 29),
        SETCOLUMNWIDTH = (LVM_FIRST + 30),
        GETHEADER = (LVM_FIRST + 31),
        CREATEDRAGIMAGE = (LVM_FIRST + 33),
        GETVIEWRECT = (LVM_FIRST + 34),
        GETTEXTCOLOR = (LVM_FIRST + 35),
        SETTEXTCOLOR = (LVM_FIRST + 36),
        GETTEXTBKCOLOR = (LVM_FIRST + 37),
        SETTEXTBKCOLOR = (LVM_FIRST + 38),
        GETTOPINDEX = (LVM_FIRST + 39),
        GETCOUNTPERPAGE = (LVM_FIRST + 40),
        GETORIGIN = (LVM_FIRST + 41),
        UPDATE = (LVM_FIRST + 42),
        SETITEMSTATE = (LVM_FIRST + 43),
        GETITEMSTATE = (LVM_FIRST + 44),
        GETITEMTEXTA = (LVM_FIRST + 45),
        GETITEMTEXTW = (LVM_FIRST + 115),
        SETITEMTEXTA = (LVM_FIRST + 46),
        SETITEMTEXTW = (LVM_FIRST + 116),
        SETITEMCOUNT = (LVM_FIRST + 47),
        SORTITEMS = (LVM_FIRST + 48),
        SETITEMPOSITION32 = (LVM_FIRST + 49),
        GETSELECTEDCOUNT = (LVM_FIRST + 50),
        GETITEMSPACING = (LVM_FIRST + 51),
        GETISEARCHSTRINGA = (LVM_FIRST + 52),
        GETISEARCHSTRINGW = (LVM_FIRST + 117),
        SETICONSPACING = (LVM_FIRST + 53),
        SETEXTENDEDLISTVIEWSTYLE = (LVM_FIRST + 54),
        GETEXTENDEDLISTVIEWSTYLE = (LVM_FIRST + 55),
        GETSUBITEMRECT = (LVM_FIRST + 56),
        SUBITEMHITTEST = (LVM_FIRST + 57),
        SETCOLUMNORDERARRAY = (LVM_FIRST + 58),
        GETCOLUMNORDERARRAY = (LVM_FIRST + 59),
        SETHOTITEM = (LVM_FIRST + 60),
        GETHOTITEM = (LVM_FIRST + 61),
        SETHOTCURSOR = (LVM_FIRST + 62),
        GETHOTCURSOR = (LVM_FIRST + 63),
        APPROXIMATEVIEWRECT = (LVM_FIRST + 64),
        SETWORKAREAS = (LVM_FIRST + 65),
        GETWORKAREAS = (LVM_FIRST + 70),
        GETNUMBEROFWORKAREAS = (LVM_FIRST + 73),
        GETSELECTIONMARK = (LVM_FIRST + 66),
        SETSELECTIONMARK = (LVM_FIRST + 67),
        SETHOVERTIME = (LVM_FIRST + 71),
        GETHOVERTIME = (LVM_FIRST + 72),
        SETTOOLTIPS = (LVM_FIRST + 74),
        GETTOOLTIPS = (LVM_FIRST + 78),
        SORTITEMSEX = (LVM_FIRST + 81),
        SETBKIMAGEA = (LVM_FIRST + 68),
        SETBKIMAGEW = (LVM_FIRST + 138),
        GETBKIMAGEA = (LVM_FIRST + 69),
        GETBKIMAGEW = (LVM_FIRST + 139),
        SETSELECTEDCOLUMN = (LVM_FIRST + 140),
        SETTILEWIDTH = (LVM_FIRST + 141),
        SETVIEW = (LVM_FIRST + 142),
        GETVIEW = (LVM_FIRST + 143),
        INSERTGROUP = (LVM_FIRST + 145),
        SETGROUPINFO = (LVM_FIRST + 147),
        GETGROUPINFO = (LVM_FIRST + 149),
        REMOVEGROUP = (LVM_FIRST + 150),
        MOVEGROUP = (LVM_FIRST + 151),
        MOVEITEMTOGROUP = (LVM_FIRST + 154),
        SETGROUPMETRICS = (LVM_FIRST + 155),
        GETGROUPMETRICS = (LVM_FIRST + 156),
        ENABLEGROUPVIEW = (LVM_FIRST + 157),
        SORTGROUPS = (LVM_FIRST + 158),
        INSERTGROUPSORTED = (LVM_FIRST + 159),
        REMOVEALLGROUPS = (LVM_FIRST + 160),
        HASGROUP = (LVM_FIRST + 161),
        SETTILEVIEWINFO = (LVM_FIRST + 162),
        GETTILEVIEWINFO = (LVM_FIRST + 163),
        SETTILEINFO = (LVM_FIRST + 164),
        GETTILEINFO = (LVM_FIRST + 165),
        SETINSERTMARK = (LVM_FIRST + 166),
        GETINSERTMARK = (LVM_FIRST + 167),
        INSERTMARKHITTEST = (LVM_FIRST + 168),
        GETINSERTMARKRECT = (LVM_FIRST + 169),
        SETINSERTMARKCOLOR = (LVM_FIRST + 170),
        GETINSERTMARKCOLOR = (LVM_FIRST + 171),
        SETINFOTIP = (LVM_FIRST + 173),
        GETSELECTEDCOLUMN = (LVM_FIRST + 174),
        ISGROUPVIEWENABLED = (LVM_FIRST + 175),
        GETOUTLINECOLOR = (LVM_FIRST + 176),
        SETOUTLINECOLOR = (LVM_FIRST + 177),
        CANCELEDITLABEL = (LVM_FIRST + 179),
        MAPINDEXTOID = (LVM_FIRST + 180),
        MAPIDTOINDEX = (LVM_FIRST + 181)
    }

    /// <summary>
    /// ListView notification message codes LVN_
    /// </summary>
    public enum LVN : int
    {
        LVN_FIRST = BaseCodes.LVN_FIRST,
        ITEMCHANGING = (LVN_FIRST - 0),
        ITEMCHANGED = (LVN_FIRST - 1),
        INSERTITEM = (LVN_FIRST - 2),
        DELETEITEM = (LVN_FIRST - 3),
        DELETEALLITEMS = (LVN_FIRST - 4),
        BEGINLABELEDITA = (LVN_FIRST - 5),
        ENDLABELEDITA = (LVN_FIRST - 6),
        COLUMNCLICK = (LVN_FIRST - 8),
        BEGINDRAG = (LVN_FIRST - 9),
        BEGINRDRAG = (LVN_FIRST - 11),
        ODCACHEHINT = (LVN_FIRST - 13),
        ITEMACTIVATE = (LVN_FIRST - 14),
        ODSTATECHANGED = (LVN_FIRST - 15),
        HOTTRACK = (LVN_FIRST - 21),
        GETDISPINFOA = (LVN_FIRST - 50),
        SETDISPINFOA = (LVN_FIRST - 51),
        ODFINDITEMA = (LVN_FIRST - 52),
        KEYDOWN = (LVN_FIRST - 55),
        MARQUEEBEGIN = (LVN_FIRST - 56),
        GETINFOTIPA = (LVN_FIRST - 57),
        GETINFOTIPW = (LVN_FIRST - 58),
        BEGINLABELEDITW = (LVN_FIRST - 75),
        ENDLABELEDITW = (LVN_FIRST - 76),
        GETDISPINFOW = (LVN_FIRST - 77),
        SETDISPINFOW = (LVN_FIRST - 78),
        ODFINDITEMW = (LVN_FIRST - 79),
        BEGINSCROLL = (LVN_FIRST - 80),
        ENDSCROLL = (LVN_FIRST - 81)
    }

    /// <summary>
    /// Notify message codes NM_
    /// </summary>
    public enum NM : int
    {
        NM_FIRST = BaseCodes.NM_FIRST,
        OUTOFMEMORY = (NM_FIRST - 1),
        CLICK = (NM_FIRST - 2),
        DBLCLK = (NM_FIRST - 3),
        RETURN = (NM_FIRST - 4),
        RCLICK = (NM_FIRST - 5),
        RDBLCLK = (NM_FIRST - 6),
        SETFOCUS = (NM_FIRST - 7),
        KILLFOCUS = (NM_FIRST - 8),
        CUSTOMDRAW = (NM_FIRST - 12),
        HOVER = (NM_FIRST - 13),
        NCHITTEST = (NM_FIRST - 14),
        KEYDOWN = (NM_FIRST - 15),
        RELEASEDCAPTURE = (NM_FIRST - 16),
        SETCURSOR = (NM_FIRST - 17),
        CHAR = (NM_FIRST - 18),
        TOOLTIPSCREATED = (NM_FIRST - 19),
        LDOWN = (NM_FIRST - 20),
        RDOWN = (NM_FIRST - 21),
        THEMECHANGED = (NM_FIRST - 22)
    }

    /// <summary>
    /// Reflected message codes OCM_
    /// </summary>
    public enum OCM : int
    {
        OCM__BASE = WM.REFLECT,
        COMMAND = (OCM__BASE + WM.COMMAND),
        CTLCOLORBTN = (OCM__BASE + WM.CTLCOLORBTN),
        CTLCOLOREDIT = (OCM__BASE + WM.CTLCOLOREDIT),
        CTLCOLORDLG = (OCM__BASE + WM.CTLCOLORDLG),
        CTLCOLORLISTBOX = (OCM__BASE + WM.CTLCOLORLISTBOX),
        CTLCOLORMSGBOX = (OCM__BASE + WM.CTLCOLORMSGBOX),
        CTLCOLORSCROLLBAR = (OCM__BASE + WM.CTLCOLORSCROLLBAR),
        CTLCOLORSTATIC = (OCM__BASE + WM.CTLCOLORSTATIC),
        CTLCOLOR = (OCM__BASE + WM.CTLCOLOR),
        DRAWITEM = (OCM__BASE + WM.DRAWITEM),
        MEASUREITEM = (OCM__BASE + WM.MEASUREITEM),
        DELETEITEM = (OCM__BASE + WM.DELETEITEM),
        VKEYTOITEM = (OCM__BASE + WM.VKEYTOITEM),
        CHARTOITEM = (OCM__BASE + WM.CHARTOITEM),
        COMPAREITEM = (OCM__BASE + WM.COMPAREITEM),
        HSCROLL = (OCM__BASE + WM.HSCROLL),
        VSCROLL = (OCM__BASE + WM.VSCROLL),
        PARENTNOTIFY = (OCM__BASE + WM.PARENTNOTIFY),
        NOTIFY = (OCM__BASE + WM.NOTIFY)
    }

    /// <summary>
    /// Windows message codes WM_
    /// </summary>
    public enum WM : int
    {
        NULL = 0x0000,
        CREATE = 0x0001,
        DESTROY = 0x0002,
        MOVE = 0x0003,
        SIZE = 0x0005,
        ACTIVATE = 0x0006,
        SETFOCUS = 0x0007,
        KILLFOCUS = 0x0008,
        ENABLE = 0x000A,
        SETREDRAW = 0x000B,
        SETTEXT = 0x000C,
        GETTEXT = 0x000D,
        GETTEXTLENGTH = 0x000E,
        PAINT = 0x000F,
        CLOSE = 0x0010,
        QUERYENDSESSION = 0x0011,
        QUIT = 0x0012,
        QUERYOPEN = 0x0013,
        ERASEBKGND = 0x0014,
        SYSCOLORCHANGE = 0x0015,
        ENDSESSION = 0x0016,
        SHOWWINDOW = 0x0018,
        CTLCOLOR = 0x0019,
        WININICHANGE = 0x001A,
        SETTINGCHANGE = 0x001A,
        DEVMODECHANGE = 0x001B,
        ACTIVATEAPP = 0x001C,
        FONTCHANGE = 0x001D,
        TIMECHANGE = 0x001E,
        CANCELMODE = 0x001F,
        SETCURSOR = 0x0020,
        MOUSEACTIVATE = 0x0021,
        CHILDACTIVATE = 0x0022,
        QUEUESYNC = 0x0023,
        GETMINMAXINFO = 0x0024,
        PAINTICON = 0x0026,
        ICONERASEBKGND = 0x0027,
        NEXTDLGCTL = 0x0028,
        SPOOLERSTATUS = 0x002A,
        DRAWITEM = 0x002B,
        MEASUREITEM = 0x002C,
        DELETEITEM = 0x002D,
        VKEYTOITEM = 0x002E,
        CHARTOITEM = 0x002F,
        SETFONT = 0x0030,
        GETFONT = 0x0031,
        SETHOTKEY = 0x0032,
        GETHOTKEY = 0x0033,
        QUERYDRAGICON = 0x0037,
        COMPAREITEM = 0x0039,
        GETOBJECT = 0x003D,
        COMPACTING = 0x0041,
        COMMNOTIFY = 0x0044,
        WINDOWPOSCHANGING = 0x0046,
        WINDOWPOSCHANGED = 0x0047,
        POWER = 0x0048,
        COPYDATA = 0x004A,
        CANCELJOURNAL = 0x004B,
        NOTIFY = 0x004E,
        INPUTLANGCHANGEREQUEST = 0x0050,
        INPUTLANGCHANGE = 0x0051,
        TCARD = 0x0052,
        HELP = 0x0053,
        USERCHANGED = 0x0054,
        NOTIFYFORMAT = 0x0055,
        CONTEXTMENU = 0x007B,
        STYLECHANGING = 0x007C,
        STYLECHANGED = 0x007D,
        DISPLAYCHANGE = 0x007E,
        GETICON = 0x007F,
        SETICON = 0x0080,
        NCCREATE = 0x0081,
        NCDESTROY = 0x0082,
        NCCALCSIZE = 0x0083,
        NCHITTEST = 0x0084,
        NCPAINT = 0x0085,
        NCACTIVATE = 0x0086,
        GETDLGCODE = 0x0087,
        SYNCPAINT = 0x0088,
        NCMOUSEMOVE = 0x00A0,
        NCLBUTTONDOWN = 0x00A1,
        NCLBUTTONUP = 0x00A2,
        NCLBUTTONDBLCLK = 0x00A3,
        NCRBUTTONDOWN = 0x00A4,
        NCRBUTTONUP = 0x00A5,
        NCRBUTTONDBLCLK = 0x00A6,
        NCMBUTTONDOWN = 0x00A7,
        NCMBUTTONUP = 0x00A8,
        NCMBUTTONDBLCLK = 0x00A9,
        KEYDOWN = 0x0100,
        KEYUP = 0x0101,
        CHAR = 0x0102,
        DEADCHAR = 0x0103,
        SYSKEYDOWN = 0x0104,
        SYSKEYUP = 0x0105,
        SYSCHAR = 0x0106,
        SYSDEADCHAR = 0x0107,
        KEYLAST = 0x0108,
        IME_STARTCOMPOSITION = 0x010D,
        IME_ENDCOMPOSITION = 0x010E,
        IME_COMPOSITION = 0x010F,
        IME_KEYLAST = 0x010F,
        INITDIALOG = 0x0110,
        COMMAND = 0x0111,
        SYSCOMMAND = 0x0112,
        TIMER = 0x0113,
        HSCROLL = 0x0114,
        VSCROLL = 0x0115,
        INITMENU = 0x0116,
        INITMENUPOPUP = 0x0117,
        MENUSELECT = 0x011F,
        MENUCHAR = 0x0120,
        ENTERIDLE = 0x0121,
        MENURBUTTONUP = 0x0122,
        MENUDRAG = 0x0123,
        MENUGETOBJECT = 0x0124,
        UNINITMENUPOPUP = 0x0125,
        MENUCOMMAND = 0x0126,
        CTLCOLORMSGBOX = 0x0132,
        CTLCOLOREDIT = 0x0133,
        CTLCOLORLISTBOX = 0x0134,
        CTLCOLORBTN = 0x0135,
        CTLCOLORDLG = 0x0136,
        CTLCOLORSCROLLBAR = 0x0137,
        CTLCOLORSTATIC = 0x0138,
        MOUSEMOVE = 0x0200,
        LBUTTONDOWN = 0x0201,
        LBUTTONUP = 0x0202,
        LBUTTONDBLCLK = 0x0203,
        RBUTTONDOWN = 0x0204,
        RBUTTONUP = 0x0205,
        RBUTTONDBLCLK = 0x0206,
        MBUTTONDOWN = 0x0207,
        MBUTTONUP = 0x0208,
        MBUTTONDBLCLK = 0x0209,
        MOUSEWHEEL = 0x020A,
        PARENTNOTIFY = 0x0210,
        ENTERMENULOOP = 0x0211,
        EXITMENULOOP = 0x0212,
        NEXTMENU = 0x0213,
        SIZING = 0x0214,
        CAPTURECHANGED = 0x0215,
        MOVING = 0x0216,
        DEVICECHANGE = 0x0219,
        MDICREATE = 0x0220,
        MDIDESTROY = 0x0221,
        MDIACTIVATE = 0x0222,
        MDIRESTORE = 0x0223,
        MDINEXT = 0x0224,
        MDIMAXIMIZE = 0x0225,
        MDITILE = 0x0226,
        MDICASCADE = 0x0227,
        MDIICONARRANGE = 0x0228,
        MDIGETACTIVE = 0x0229,
        MDISETMENU = 0x0230,
        ENTERSIZEMOVE = 0x0231,
        EXITSIZEMOVE = 0x0232,
        DROPFILES = 0x0233,
        MDIREFRESHMENU = 0x0234,
        IME_SETCONTEXT = 0x0281,
        IME_NOTIFY = 0x0282,
        IME_CONTROL = 0x0283,
        IME_COMPOSITIONFULL = 0x0284,
        IME_SELECT = 0x0285,
        IME_CHAR = 0x0286,
        IME_REQUEST = 0x0288,
        IME_KEYDOWN = 0x0290,
        IME_KEYUP = 0x0291,
        MOUSEHOVER = 0x02A1,
        MOUSELEAVE = 0x02A3,
        CUT = 0x0300,
        COPY = 0x0301,
        PASTE = 0x0302,
        CLEAR = 0x0303,
        UNDO = 0x0304,
        RENDERFORMAT = 0x0305,
        RENDERALLFORMATS = 0x0306,
        DESTROYCLIPBOARD = 0x0307,
        DRAWCLIPBOARD = 0x0308,
        PAINTCLIPBOARD = 0x0309,
        VSCROLLCLIPBOARD = 0x030A,
        SIZECLIPBOARD = 0x030B,
        ASKCBFORMATNAME = 0x030C,
        CHANGECBCHAIN = 0x030D,
        HSCROLLCLIPBOARD = 0x030E,
        QUERYNEWPALETTE = 0x030F,
        PALETTEISCHANGING = 0x0310,
        PALETTECHANGED = 0x0311,
        HOTKEY = 0x0312,
        PRINT = 0x0317,
        PRINTCLIENT = 0x0318,
        HANDHELDFIRST = 0x0358,
        HANDHELDLAST = 0x035F,
        AFXFIRST = 0x0360,
        AFXLAST = 0x037F,
        PENWINFIRST = 0x0380,
        PENWINLAST = 0x038F,
        APP = 0x8000,
        USER = 0x0400,
        REFLECT = USER + 0x1c00
    }
}
